Usuario poder criar o Galo
Super-Projetos-Engenharia-Unicesumar/rinha_baixo_nivel pull request #5
Opened 2020-11-23 00:59 UTC by matheusvodag

2020-11-24 00:42 UTC, shinspiegel requested changes
Coloquei umas considerações a respeito do código.
Para praticar como é feito a revisão de código.

2020-11-24 00:42 UTC, shinspiegel commented on src/cock.c
> +    int defCock;
Geralmente se coloca todas as variáveis no início do bloco, assim fica fácil localizar e encontrar os tipos dela quando precisa entender o que elas são.

2020-11-24 00:42 UTC, shinspiegel commented on src/cock.c
> +    int opt;
Assim como o outro, nesse caso movimenta essa variável para o incio desse escopo.

2020-11-24 00:42 UTC, shinspiegel commented on src/cock.c
> +    }
Tem que ajustar a indentação desse aqui, os `cases` tem que ficar com uma indentação adentro do código para ficar corretamente.

2020-11-25 01:13 UTC, matheusvodag commented on src/cock.c
> +    int defCock;
deixa de ser chata

2020-11-25 01:14 UTC, matheusvodag commented on src/cock.c
> +    }
https://www.catalogo.med.br/medicos/psiquiatras/em-sc/

2020-11-25 01:55 UTC, merged